export enum NotificationType {
  BREAKDOWN_CREATED = 'BREAKDOWN_CREATED',
  PROVIDER_ASSIGNED = 'PROVIDER_ASSIGNED',
  PROVIDER_ARRIVED = 'PROVIDER_ARRIVED',
  REQUEST_COMPLETED = 'REQUEST_COMPLETED',
  REQUEST_CANCELLED = 'REQUEST_CANCELLED',
  EMERGENCY_ALERT = 'EMERGENCY_ALERT',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  ADMIN_BROADCAST = 'ADMIN_BROADCAST',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  PUSH = 'PUSH',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  READ = 'READ',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  EMERGENCY = 'EMERGENCY',
}
