export enum IssueType {
  FLAT_TIRE = 'FLAT_TIRE',
  BATTERY_FAILURE = 'BATTERY_FAILURE',
  FUEL_EMPTY = 'FUEL_EMPTY',
  ENGINE_FAILURE = 'ENGINE_FAILURE',
  ACCIDENT = 'ACCIDENT',
  BRAKE_FAILURE = 'BRAKE_FAILURE',
  OVERHEATING = 'OVERHEATING',
  LOCKOUT = 'LOCKOUT',
  EV_BATTERY_LOW = 'EV_BATTERY_LOW',
}

export enum RequestPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  EMERGENCY = 'EMERGENCY',
}

export enum BreakdownStatus {
  CREATED = 'CREATED',
  SEARCHING_PROVIDER = 'SEARCHING_PROVIDER',
  PROVIDER_ASSIGNED = 'PROVIDER_ASSIGNED',
  ON_THE_WAY = 'ON_THE_WAY',
  ARRIVED = 'ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
